id: P000597
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16714
  title: གསུང་འབུམ། བློ་གཏེར་དབང་པོ།
  author: ''
  volumes:
    a9faf3a7096d4fcd9242368788e019ad:
      image_group_id: I2PD18513
      title: ''
      volume_number: 1
      total_pages: 330
    8adfc6c9fe5b480c8a026b77864cc272:
      image_group_id: I2PD18514
      title: ''
      volume_number: 2
      total_pages: 488
    598d9a7e269b4d17a395335e34b36db0:
      image_group_id: I2PD18515
      title: ''
      volume_number: 3
      total_pages: 312
    b32c1222067e4b98b7b88605ba626ef4:
      image_group_id: I2PD18516
      title: ''
      volume_number: 4
      total_pages: 340
    d6ec447ebe0a490bb4814202919bd076:
      image_group_id: I2PD18517
      title: ''
      volume_number: 5
      total_pages: 410
    0046584298fc4926b41094a0727ca68f:
      image_group_id: I2PD18518
      title: ''
      volume_number: 6
      total_pages: 450
