id: I4BF0FE25
legacy_id: P000597
ocr_import_info:
  bdrc_scan_id: W1KG16714
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T20:21:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:10:47.807191+00:00'
last_modified: 2022-08-27 14:14:31.715446
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16714
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16714
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་གཏེར་དབང་པོ།
  author: ངོར་པ་དཔོན་སློབ་བློ་གཏེར་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9325828664063586
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD18513:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18513
      total_pages: 330
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18513.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9589696073748966
    legacy_id: v001
  I2PD18515:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18515
      total_pages: 312
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD18515.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9660137189501112
    legacy_id: v003
  I2PD18516:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18516
      total_pages: 340
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD18516.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9461796808554424
    legacy_id: v004
  I2PD18517:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18517
      total_pages: 410
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD18517.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9601891664623029
    legacy_id: v005
  I2PD18514:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18514
      total_pages: 488
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD18514.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8851632761195581
    legacy_id: v002
  I2PD18518:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18518
      total_pages: 450
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2PD18518.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.939525251254327
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
